# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 08:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('f', models.FileField(upload_to='')),
            ],
        ),
        migrations.AddField(
            model_name='passage',
            name='tags',
            field=models.CharField(default='', max_length=1024),
            preserve_default=False,
        ),
    ]
