# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:27
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20171123_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
