# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-23 09:46
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20171123_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passage',
            name='body',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
